apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
   app: helloworld
   version: v.2
spec:
  selector:
   matchLabels:
    app: helloworld  
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      imagePullSecrets:
      - name: private-registry-key
      containers:
      - name: mo-demo
        image: nadpereira/relautimages:mo.v.2
        ports:
        - name: nodejs-port
          containerPort: 3000
        livenessProbe:
         httpGet:
          path: /
          port: nodejs-port
         initialDelaySeconds: 15
         timeoutSeconds: 30