apiVersion: v1
kind: Pod
metadata:
 name: mo-helloworld
 labels:
   app: helloworld
   version: v.2
spec:
 imagePullSecrets:
 - name: private-registry-key
 containers:
  - name: moksh
    image: nadpereira/relautimages:mo.v.2
    ports:
    - name: nodejs-port
      containerPort: 3000