apiVersion: v1
kind: Pod
metadata:
 name: mo-helloworld
 labels:
   app: helloworld
   version: v.1
spec:
 containers:
   - name: moksh
     image: nadpereira/relautimages:mo.v.1
     ports:
     - name: nodejs-port
       containerPort: 3000
 