apiVersion: v1
kind: ReplicationController
metadata:
  name: mo-helloworld-controller
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      imagePullSecrets:
      - name: private-registry-key
      containers:
      - name: mo-first
        image: nadpereira/relautimages:mo.v.2
        ports:
        - name: nodejs-port
          containerPort: 3000